#services:
#  roomreservation:
#    image: roomreservation
#    build:
#      context: .
#      dockerfile: src/RoomReservation.API/Dockerfile

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: RoomReservation.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Default: "Server=db;Database=Room;User=sa;Password=Pass123!;"